layout_spectrum: 0.4907981439027935
typography_spectrum: 0.9810442037414759
color:
  brandColors:
    - '#67bc00'
    - '#ffffff'
    - '#595959'
    - '#9c9c9c'
    - '#0001fb'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Amr
  email: amorselim@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3872a65a-dae1-4f3b-800a-ca9e0410cc11.jpg
name: HumanTalents Canada
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: HumanTalents Main Page
    url: 'http://humantalents.ca/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/eb65dcbd-ebde-4b80-abb2-155add264b24.ico
title: Your Partners in Customer Success
description: 'Helping you Attract, Train And Retain the best Talent'
purpose: []
