name: HT.CA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15352
title: HumanTalents Development Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#7eba42'
    - '#233f93'
    - '#bad8a1'
    - '#7079ac'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
