name: HT.CA
favicon: null
layout_spectrum: 0.7963386948686093
typography_spectrum: 0.45614737388677895
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#000000'
    - '#909090'
    - '#3b3b3b'
    - '#db63f3'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
