name: HT.CA
favicon: null
layout_spectrum: 0.51294
typography_spectrum: 0.74655
title: HumanTalents Development Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#cec9d0'
    - '#050409'
    - '#af6d4d'
    - '#574b4f'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
