typography_spectrum: 0.15352
color:
  brandColors:
    - '#67bc00'
    - '#ffffff'
    - '#595959'
    - '#9c9c9c'
    - '#0001fb'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26068
analytics:
  google: null
  facebook: null
  twitter: null
name: HumanTalents CA
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: HumanTalents CANADA
purpose: []
